import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { ReactNode } from "react";

import "./globals.scss";

const ralewaySans = Raleway({
  variable: "--font-raleway-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Test next app",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="uk">
      <body className={ralewaySans.variable}>{children}</body>
    </html>
  );
}
